import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/modules/layout/Navbar";
import { Particles } from "@/components/ui/shadcn-io/particles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Toaster position="bottom-right" gutter={10} />
          <Particles
            className="inset-0 fixed min-w-screen min-h-screen -z-40"
            quantity={100}
            ease={80}
            staticity={50}
            color="accent"
            size={0.8}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
